#!/usr/bin/env node
/* =========================================================================
   build-config — projects site.config.mjs into the two places that cannot
   import an ES module.

     api/site.config.generated.cjs   api/ is CommonJS, because that is the
                                     Vercel function idiom and because
                                     calendar-categorize.test.mjs require()s
                                     it. A generated CJS mirror lets
                                     api/calendar.js read the config
                                     synchronously at module load, so
                                     categorize() stays a plain function.

     vercel.json                     Six near-identical redirect stanzas for
                                     three alias hosts, which nobody should
                                     write by hand.

   Both outputs are committed, exactly like blog/ and programs/. Re-run this
   after editing site.config.mjs.

   It also checks the one value that is duplicated by necessity: the
   theme-color meta tag lives in the config, the palette lives in styles.css,
   and they have to agree.

     node scripts/build-config.mjs
   ========================================================================= */
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import config from '../site.config.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');

function fail(msg) {
  console.error('build-config: ' + msg);
  process.exit(1);
}

/* ---------- theme-color must match --blue ---------- */

const css = readFileSync(join(ROOT, 'styles.css'), 'utf8');
const blue = (/--blue:\s*(#[0-9a-fA-F]{3,8})\s*;/.exec(css) || [])[1];
if (!blue) fail('could not find --blue in styles.css');
if (blue.toLowerCase() !== config.theme.themeColor.toLowerCase()) {
  fail('theme.themeColor (' + config.theme.themeColor + ') does not match --blue (' + blue + ') in styles.css.\n'
    + '  These paint the same brand color in two places the browser reads separately.\n'
    + '  Change both, or change styles.css and copy the value into site.config.mjs.');
}

/* ---------- api/site.config.generated.cjs ---------- */

const banner = '/* GENERATED by scripts/build-config.mjs — do not edit.\n'
  + '   Edit site.config.mjs and re-run the build. This exists because api/ is\n'
  + '   CommonJS and cannot import an .mjs module. */\n';

writeFileSync(
  join(ROOT, 'api', 'site.config.generated.cjs'),
  banner + 'module.exports = ' + JSON.stringify(config, null, 2) + ';\n'
);

/* ---------- vercel.json ---------- */

const { deploy } = config;
const canonical = 'https://' + deploy.canonicalHost;

const redirects = (deploy.redirects || []).map((r) => ({
  source: r.from,
  destination: r.to,
  permanent: true,
}));

// Apex and every path, per alias host. Two stanzas each because a wildcard
// ":path*" does not match the bare "/".
for (const host of deploy.aliasHosts || []) {
  redirects.push({
    source: '/',
    has: [{ type: 'host', value: host }],
    destination: canonical + '/',
    permanent: true,
  });
  redirects.push({
    source: '/:path*',
    has: [{ type: 'host', value: host }],
    destination: canonical + '/:path*',
    permanent: true,
  });
}

const vercel = {
  $schema: 'https://openapi.vercel.sh/vercel.json',
  cleanUrls: true,
  rewrites: [
    // Calendar apps are fussy about subscribe URLs: several match on a literal
    // .ics extension and choke on a query string, so the clean paths exist
    // alongside the ?format=ics the site's own fetch uses.
    { source: '/calendar.ics', destination: '/api/calendar?format=ics' },
    { source: '/calendar-:only.ics', destination: '/api/calendar?format=ics&only=:only' },
  ],
  redirects,
};

writeFileSync(join(ROOT, 'vercel.json'), JSON.stringify(vercel, null, 2) + '\n');

console.log('build-config: wrote api/site.config.generated.cjs + vercel.json ('
  + redirects.length + ' redirects)');
